language: scala
scala:
  - 2.10.4
script:
  - sbt -Dcapsulecrm.url=https://coen.capsulecrm.com -Dcapsulecrm.token=$CAPSULECRM_TOKEN ++$TRAVIS_SCALA_VERSION assembly
env:
  global:
    - secure: Pjq8livIaI8xzA8aU+/y5/IfppkUIgpMEOXX+ckktEWab1eBSaBDUO4FMBwl7TAUWSlq4Skg7Bst182eRohjAd/EpVsz51hVr/drWzyscHvj7dnlVrBa9S5CRXgTKv0MJl/h2EhqO4bzcdxs59PTbYCMlplcFAPA301O+g3qy8U=